services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:15.0.9
    container_name: forgejo
    restart: unless-stopped

    environment:
      USER_UID: ${PUID}
      USER_GID: ${PGID}

      FORGEJO____APP_NAME: ${FORGEJO_APP_NAME}

      FORGEJO__database__DB_TYPE: sqlite3

      FORGEJO__server__DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__ROOT_URL: ${FORGEJO_ROOT_URL}
      FORGEJO__server__SSH_DOMAIN: ${FORGEJO_SSH_DOMAIN}
      FORGEJO__server__SSH_PORT: "${FORGEJO_SSH_PORT}"

      FORGEJO__service__DISABLE_REGISTRATION: "true"

    ports:
      - "${FORGEJO_HTTP_PORT}:3000"
      - "${FORGEJO_SSH_PORT}:22"

    volumes:
      - /srv/docker/data/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
