services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/data/dockge:/app/data
      - /srv/docker/compose:/srv/docker/compose
    environment:
      - DOCKGE_STACKS_DIR=/srv/docker/compose
      - PUID=${PUID}
      - PGID=${PGID}
